### ISSUE TITLE
Graph lines blinking on (re)load

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#224] opened 2018-02-05 17:09 UTC
![blink](https://user-images.githubusercontent.com/46439/35818149-420412a0-0a6d-11e8-8fe0-70967105f0e2.gif)

They load, then go white, then show again

**Comment by pkarman** [comment] 2018-02-05 17:11
dupe of #211

**Closed by pkarman** 2018-02-05 17:11 UTC
