### ISSUE TITLE
Hard to tell which page is active

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#163] opened 2018-01-17 15:01 UTC
![image](https://user-images.githubusercontent.com/3483/35049184-2ee57a6a-fb6d-11e7-98df-4a3bd7935a8a.png)

Likely this will get covered by #162 but in the interim might be good to add some contrast

**Comment by sandikbarr** [comment] 2018-01-17 15:37
Duplicate of https://github.com/PRX/styleguide.prx.org/issues/83

**Comment by pkarman** [comment] 2018-01-19 15:55
closing as dupe

**Closed by pkarman** 2018-01-19 15:55 UTC
