### ISSUE TITLE
Hourly tick marks become a blur

### ISSUE THREAD

**Issue by cavis** [PRX/metrics.prx.org#229] opened 2018-02-05 17:20 UTC
When looking at 30 days hourly, the tick marks become a blur, and the labels get a little wonky as well.

![image](http://cav.is/i/ahg60.jpg)

**Comment by sandikbarr** [comment] 2018-02-05 17:24
related to https://github.com/PRX/metrics.prx.org/issues/176

**Comment by pkarman** [comment] 2018-02-07 16:26
dupe of #176

**Closed by pkarman** 2018-02-07 16:26 UTC
Labels: medium
