### ISSUE TITLE
Improve design of paging control

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#162] opened 2018-01-17 14:59 UTC
![image](https://user-images.githubusercontent.com/3483/35049162-19a93f6a-fb6d-11e7-8511-469a0d2bf782.png)

This could use a more polished final design

**Comment by kookster** [comment] 2018-01-17 15:04
that sounds like you're volunteering to provide some polish, maybe? ;)

**Comment by pkarman** [comment] 2018-01-17 16:54
@farski I am assigning to you for design work. Please add an Estimate so we can get this in the next sprint.

**Comment by pkarman** [comment] 2018-01-17 16:56
Actually this is a duplicate of https://github.com/prx/styleguide.prx.org/issues/83 which is already groomed. Closing this and assigning that one to @farski

**Closed by pkarman** 2018-01-17 16:56 UTC
Labels: high
