### ISSUE TITLE
Navigating Back in browser requires re-authentication

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#85] opened 2017-11-27 20:34 UTC
Seems like any time I navigate back to metrics from an external site it will ask me to log in again

**Comment by sandikbarr** [comment] 2017-11-28 17:32
Noting that Publish also has this issue.

**Comment by sandikbarr** [comment] 2017-12-11 21:38
Need to look into what the issue is in order to provide an estimate. The work will be done in the styleguide since the auth is over there, and this will be a problem for all our front end apps using it.

**Comment by kookster** [comment] 2018-01-09 16:14
I too see this, clicking on the `about` link in the footer for example.

It seems to only happen when going out to the exchange app (www.prx.org) and then going back.
Going back from help.prx.org, blog.prx.org, matter ventures, or radiotopia do not lead to login.

It seems likely to me this has something to do with exchange messing with the cookies and session - we have tried to make exchange and id logins compatible, but perhaps there is some flaw in it.

**Comment by kookster** [comment] 2018-01-09 16:15
(I don't know exactly what the problem is, but I think the fix for this is likely to be made in exchange or id, not in metrics or publish)

**Closed** 2018-01-18 15:08 UTC
Labels: bug, high
