### ISSUE TITLE
Seems like clicking show image in profile should take you to Podcast chart

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#218] opened 2018-02-05 17:00 UTC
I keep clicking on the show image and expecting it to take me to the Podcast chart (or undo the sole-selection-of-most-recent-ep that happened when I clicked on the episode title in profile section)
![image](https://user-images.githubusercontent.com/16007382/35817680-1e83d12c-0a6c-11e8-9b5e-b6903627eeea.png)

**Comment by sandikbarr** [comment] 2018-02-20 17:05
@farski what are your thoughts on the podcast profile picture being used as a navigational element?

**Comment by sandikbarr** [comment] 2018-06-12 18:20
show image removed, ice boxing. If we bring it back, can we talk about why it's using a 50% border radius when podcast cover images are square by design?

**Comment by sandikbarr** [comment] 2019-04-09 19:54
removed, closing

**Closed by sandikbarr** 2019-04-09 19:54 UTC
Labels: medium
